<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Siswa; 

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $siswa = Siswa::insert([
            [
                'nama' => 'ABU BAKAR TSABIT GHUFRON',  
                'gambar' => 'images/siswa.jpg',
                'nis' => '20388',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '085839328609',
                'email' => 'abu@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ADE RAFIF DANESWARA',  
                'gambar' => 'images/siswa.jpg',
                'nis' => '20389', 
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '08983688325',
                'email' => 'aderafif@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ADE ZAIDAN ALTHAF', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20390',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'ade@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ADHWA KHALILA RAMADHANI',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20391',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'adhwa@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ADNAN FARIS', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20392',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'adnan@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'AHMAD HANAFI', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20393',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'ahmad@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'AKBAR ADHA KUSUMAWARDANA',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20394',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'akbar@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ANDHIKA AUGUST FARNAS',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20395',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'andhika@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ANGELINA THITHIS SEKAR LANGIT',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20396',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'angelina@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ARIFIN NUR IKHSAN', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20397',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'arifin@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ARYA EKA RAHMAT PRASETYA', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20398',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'arya@gmail.com', // PERBAIKAN: Menambahkan @ yang hilang
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ATHIYYA HANIIFA', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20399',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'athiyya@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'AULIA MAHARANI', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20400',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'aulia@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'BIJAK PUTRA FIRMANSYAH',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20401',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'bijak@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'CHRISTIAN JARROT FERDIAN NDARU',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20402',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'christian@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'DAFFA ARYA SETA', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20403',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'daffa@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'DIMAS BAGUS AHMAD NURYASIN',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20404',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'dimas@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'EKALAYA KEMAL PASHA',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20405',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'ekalaya@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'FADLY ATHALLA FAWWAZ',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20406',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'fadly@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'FARADILLA SYIFA NUR\'AINI', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20407',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'faradilla@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'FARCHA AMALIA NUGRAHAINI',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20408',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'farcha@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'FAUZAN ADZIMA KURNIAWAN',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20409',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'fauzan@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'GABRIEL POSSENTI GENTA BAHANA NAGARI',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20410',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'gabriel@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'GILANG NURHUDA', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20411',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'gilang@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'GISELO KRISTIYANTO', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20412',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'giselo@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ILHAM PUTRA MAHENDRA',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20413',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'ilham@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'INTAN LUVIA HISANAH',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20414',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'intan@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'ISNAINI NUR WAHYUNINGSIH',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20415',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'isnaini@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'IZZUDIN FAYYEDH HAQ',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20416',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'izzudin@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'JARDELLA ANGGUN LAVATEKTONIA', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20417',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'jardella@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'JECONIA VALE ADYATMA',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20418',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'jeconia@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'KEVIN ANDREA GERALDINO',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20419',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'kevin@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'KASYA AQILA AMTA', 
                'gambar' => 'images/siswa.jpg',
                'nis' => '20420',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'kasya@gmail.com', // PERBAIKAN: Mengganti 'kaysa' dengan 'kasya' sesuai nama
                'status_pkl'=> false,
            ],
            [
                'nama' => 'LAURENTIUS DAVIANUS MAXIMUS ANTARA',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20421',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'laurentius@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'MARCHELLINUS CHRISTO PRADIPTA',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20422',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'marchellinus@gmail.com',
                'status_pkl'=> false,
            ],
            [
                'nama' => 'MEIDINNA TIARA PRAMUDHITA',
                'gambar' => 'images/siswa.jpg', 
                'nis' => '20423',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087786760589',
                'email' => 'meidinna@gmail.com', 
                'status_pkl'=> false,
            ],
        ]);
    }
}